version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Reduce PR limit significantly to force better grouping
    open-pull-requests-limit: 3
    reviewers:
      - "SantoshDasari-ai"
    assignees:
      - "SantoshDasari-ai"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

    # Comprehensive grouping strategy to minimize PRs
    groups:
      # Group ALL production dependencies together
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

      # Group ALL development dependencies together
      development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

      # Separate group for security updates (highest priority)
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
        # This will catch security patches regardless of dep type

      # Major updates get their own group (manual review required)
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

    # Auto-approve safe updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

    # Simplified labels
    labels:
      - "dependencies"
      - "automated"

    # Ignore problematic packages
    ignore:
      - dependency-name: "node"
        versions: ["< 18.0.0"]

  # Simplified GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "SantoshDasari-ai"
    assignees:
      - "SantoshDasari-ai"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
    # Group all GitHub Actions together
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
