name: Auto-merge Dependabot PRs

"on":
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # Every Tuesday at 10:00 UTC
    - cron: "0 10 * * 2"
  workflow_dispatch:

# Prevent several overlapping runs when Dependabot opens many PRs
concurrency:
  group: dependabot-auto-merge
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' || github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y jq          # explicit – don’t rely on image default

      - name: Set up GitHub CLI
        run: |
          # GitHub CLI is pre-installed on ubuntu-latest runners
          gh --version

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Find & merge green Dependabot PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PRS=$(gh pr list --author "app/dependabot" --state open --json number --jq '.[].number')
          if [ -z "$PRS" ]; then
            echo "No Dependabot PRs open"; exit 0
          fi

          for PR in $PRS; do
            echo "▶ Evaluating PR #$PR"
            RED=$(gh pr view "$PR" --json statusCheckRollup --jq \
              '.statusCheckRollup[] | select(.state!="SUCCESS") | .name' || true)
            if [ -n "$RED" ]; then
              echo "⏭  Skipping – some checks not green:"
              echo "$RED"
              continue
            fi
            gh pr merge "$PR" --squash --delete-branch --auto
          done
