name: CI

"on":
  push:
    branches: [main]
  pull_request:
  schedule:
    # Every Monday at 08:00 UTC
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  security-events: write

# Cancel superseded runs (e.g. a force-push)
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# -------- existing job definitions start below --------
jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npx prettier --check .

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm test --if-present

  security-audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm audit --audit-level=high

  ci-complete:
    runs-on: ubuntu-latest
    needs: [lint, build, test, security-audit]
    steps:
      - name: Gate
        run: |
          echo "All required jobs succeeded 🎉"
