name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Type of test to run"
        required: true
        default: "build"
        type: choice
        options: ["build", "lint", "security", "all"]

jobs:
  manual-test:
    runs-on: ubuntu-latest
    name: Manual Test – ${{ github.event.inputs.test_type }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: Run Lint
        if: ${{ github.event.inputs.test_type == 'lint' || github.event.inputs.test_type == 'all' }}
        run: npm run lint

      - name: Run Build
        if: ${{ github.event.inputs.test_type == 'build' || github.event.inputs.test_type == 'all' }}
        run: npm run build

      - name: Run Security Audit
        if: ${{ github.event.inputs.test_type == 'security' || github.event.inputs.test_type == 'all' }}
        run: npm audit --audit-level=high
